version: '1'
services:
  postgres:
    image: postgres:latest
    container_name: socks-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: SocksStock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: